services:
  wormhole-mailox:
    build: 
     context: ./mailbox-server
     dockerfile: Dockerfile
    ports:
      - "4000:4000"
    restart: unless-stopped
  wormhole-transit:
    build: 
      context: ./transit-relay
      dockerfile: Dockerfile
    ports:
      - "4001:4001"
    restart: unless-stopped
